# Copyright (c) MyoSuite Authors. All rights reserved.
#
# This source code is licensed under the Apache 2 license found in the
# LICENSE file in the root directory of this source tree.

"""Numerical parity tests against frozen baselines.

For each env that has a corresponding .pkl in parity_baselines/, replays the
stored action sequence and asserts that observations, rewards, and termination
flags are bit-identical (within float32 tolerance).

Baseline format: list of dicts with keys:
    action, obs, rwd, terminated, truncated, info, episode_np_state

Before replaying each episode, the env's internal np_random bit-generator state
is restored to the saved value and env.reset() is called. This makes the
trajectory deterministic even though the env does not propagate seed through
env.reset(seed=...) in the current codebase.

Baselines are generated by:
    python scripts/generate_parity_baselines.py --env-id <env-id>
"""

from __future__ import annotations

import pickle
from pathlib import Path

import numpy as np
import pytest

import myosuite
from myosuite.utils import gym

myosuite.register_all_envs()


pytestmark = pytest.mark.tier1

BASELINE_DIR = Path(__file__).parent / "parity_baselines"

# Envs whose reset() uses collision-avoidance loops can resample goal/object
# poses, so replay may not match baseline exactly; use looser obs atol.
RELAXED_OBS_ATOL: dict[str, float] = {
    # Goal / object resampling + cross-platform MuJoCo drift can exceed 1.0 on
    # some runners while still matching the intended replay contract.
    "myoChallengeRelocateP1-v0": 4.0,
    "myoChallengeRelocateP2-v0": 0.2,
    "myoChallengeRelocateP2eval-v0": 0.2,
    # Cross-platform MuJoCo minor drift (arm64 vs x86_64) for these tasks.
    "myoFingerPoseFixed-v0": 2e-3,
    "myoFingerPoseRandom-v0": 2e-3,
    "myoHandPoseRandom-v0": 5e-4,
    # Baseline regenerated after fixing the missing contype/conaffinity on the
    # SAR reorient object (it previously free-fell untouched, unskippable
    # nondeterminism from uncontrolled contact ordering). Now deterministic at
    # 1e-6 locally; kept relaxed for cross-platform MuJoCo/BLAS drift margin,
    # same as the other envs in this table.
    "myoHandReorient8-v0": 1.0,
    # Contact-solver floating-point nondeterminism: obs match to 6+ significant
    # figures for the first ~25 steps, then diverge sharply at a single step
    # (observed max |dobs| 4.22e-5) - the classic signature of contact-order
    # drift, not a logic regression. myoLegRoughTerrainWalk-v0 shows the same
    # pattern but the divergence keeps growing over the full episode (up to
    # 1.36e-4 by step 115 on uneven-terrain contact events), so it is treated
    # as nondeterministic below rather than given an ever-growing atol.
    "myoLegWalk-v0": 1e-4,
}
RELAXED_RWD_ATOL: dict[str, float] = {
    "myoChallengeRelocateP1-v0": 25.0,
    "myoChallengeRelocateP2-v0": 20.0,
    "myoChallengeRelocateP2eval-v0": 20.0,
    "myoFingerPoseFixed-v0": 5e-4,
    "myoFingerPoseRandom-v0": 5e-4,
    "myoHandPoseRandom-v0": 5e-4,
    # Step-50 reward drift ~1e-3 on arm64 vs baseline capture (obs atol already 1e-2).
    "myoHandReorient8-v0": 1e-2,
    # Reward is a function of the obs positions relaxed above; give it the same
    # contact-order-drift margin.
    "myoLegWalk-v0": 1e-2,
}
# Finger-pose environments show occasional branch divergence in long baseline
# replays on Linux/x86 CI runners (goal resets in nested wrappers can drift by
# one branch after ~100 steps). Keep parity coverage on deterministic envs.
NONDETERMINISTIC_PARITY_ENVS: set[str] = {
    "myoFingerPoseFixed-v0",
    "myoFingerPoseRandom-v0",
    # Rough-terrain foot contact ordering: obs match to 6+ significant figures
    # early on, then diverge further with episode length (unbounded, unlike
    # myoLegWalk-v0's single-step jump covered by RELAXED_OBS_ATOL above).
    "myoLegRoughTerrainWalk-v0",
}


def _get_baseline_env_ids() -> list[str]:
    """Return env IDs that have a .pkl baseline file."""
    return [p.stem for p in sorted(BASELINE_DIR.glob("*.pkl"))]


@pytest.mark.parametrize("env_id", _get_baseline_env_ids())
def test_parity(env_id: str) -> None:
    """Replay frozen action sequence and assert numerical parity."""
    if env_id in NONDETERMINISTIC_PARITY_ENVS:
        pytest.skip(
            f"{env_id} baseline replay is non-deterministic on CI runners; "
            "tracked separately from strict parity gates."
        )

    pkl_path = BASELINE_DIR / f"{env_id}.pkl"

    with open(pkl_path, "rb") as fh:
        records: list[dict] = pickle.load(fh)

    try:
        env = gym.make(env_id)
    except Exception as exc:
        pytest.skip(f"Cannot instantiate {env_id}: {exc}")

    try:
        env.reset()
        current_episode_np_state = None

        for i, rec in enumerate(records):
            # When a new episode starts (np_state differs), restore the saved
            # RNG state and call env.reset() to reproduce the same initial obs.
            if rec["episode_np_state"] is not current_episode_np_state:
                current_episode_np_state = rec["episode_np_state"]
                env.unwrapped.np_random.bit_generator.state = current_episode_np_state
                env.reset()

            obs, rwd, terminated, truncated, _ = env.step(rec["action"])

            atol = RELAXED_OBS_ATOL.get(env_id, 1e-6)
            np.testing.assert_allclose(
                obs,
                rec["obs"],
                atol=atol,
                err_msg=f"{env_id} step {i}: obs mismatch",
            )
            rwd_atol = RELAXED_RWD_ATOL.get(env_id, 1e-6)
            assert (
                abs(rwd - rec["rwd"]) < rwd_atol
            ), f"{env_id} step {i}: reward mismatch (got {rwd}, expected {rec['rwd']})"
            assert (
                terminated == rec["terminated"]
            ), f"{env_id} step {i}: terminated mismatch"
    finally:
        env.close()
