# Copyright (c) MyoSuite Authors. All rights reserved.
#
# This source code is licensed under the Apache 2 license found in the
# LICENSE file in the root directory of this source tree.

"""Numerical parity tests against frozen baselines.

For each env that has a corresponding .pkl in parity_baselines/, replays the
stored action sequence and asserts that the observations and rewards match
within atol 1e-6 (or a per-env relaxed tolerance, each with a measured reason)
and that the terminated and truncated flags are identical.

Baseline format: list of dicts with keys:
    action, obs, rwd, terminated, truncated, info, episode_np_state

Before replaying each episode, the env's internal np_random bit-generator state
is restored to the saved value and env.reset() is called. This makes the
trajectory deterministic even though the env does not propagate seed through
env.reset(seed=...) in the current codebase.

Baselines are generated by:
    python scripts/generate_parity_baselines.py --env-id <env-id>
"""

from __future__ import annotations

import pickle
from pathlib import Path

import numpy as np
import pytest

import myosuite
from myosuite.utils import gym

myosuite.register_all_envs()


pytestmark = pytest.mark.tier1

BASELINE_DIR = Path(__file__).parent / "parity_baselines"

# Per-env obs atol overrides of the strict 1e-6 default; each needs a reason.
# Every replay is deterministic on one machine (bit-identical in-process and
# across processes); the margins cover drift between platforms and machines.
RELAXED_OBS_ATOL: dict[str, float] = {
    # Cross-platform MuJoCo minor drift (arm64 vs x86_64) for these tasks. The
    # finger baselines hold one episode only (see the generator's
    # N_STEPS_OVERRIDES): the second episode of the seed-42 action stream is
    # ill-conditioned (a 1e-12 qpos offset at reset grows past 3e-3 by step 158),
    # while the first episode of the previous, macOS-made baseline replayed
    # within 1.3e-3 obs / 3.2e-4 reward on x86-64 Windows.
    "myoFingerPoseFixed-v0": 2e-3,
    "myoFingerPoseRandom-v0": 2e-3,
    "myoHandPoseRandom-v0": 5e-4,
    # Bit-exact across processes on one machine; on another x86-64 machine the
    # obs jump by up to 7.5e-4 at isolated steps (the first at step 40), and a
    # 1e-14 qpos offset at reset already causes a 4.4e-4 jump. The margin also
    # covers the arm64 drift recorded for this env (reward below).
    "myoHandReorient8-v0": 1e-2,
    # Contact-solver floating-point drift: obs match to 6+ significant figures
    # for the first ~25 steps, then jump at a single step (observed max |dobs|
    # 4.22e-5), the signature of contact-order drift, not a logic regression.
    "myoLegWalk-v0": 1e-4,
    # Same leg model on uneven terrain; cross-platform drift of up to 1.36e-4 by
    # step 115 was recorded before #444 regenerated the baseline. The current
    # replay is well-conditioned (a 1e-9 qpos offset at reset moves the obs by
    # at most 2.4e-7), so 1e-3 covers the recorded drift with margin.
    "myoLegRoughTerrainWalk-v0": 1e-3,
    # Contact-rich; the baseline was captured on Windows. On Linux/x86_64 the
    # obs drift by up to 1.5e-5 from step ~30 (contact-order drift), reward by 7e-9.
    "myoChallengeRelocateP1-v0": 1e-4,
}
RELAXED_RWD_ATOL: dict[str, float] = {
    "myoFingerPoseFixed-v0": 5e-4,
    "myoFingerPoseRandom-v0": 5e-4,
    "myoHandPoseRandom-v0": 5e-4,
    # Step-50 reward drift ~1e-3 on arm64 vs baseline capture.
    "myoHandReorient8-v0": 1e-2,
    # Reward is a function of the obs positions relaxed above; give it the same
    # contact-order-drift margin (per-step reward changes have median 0.3-0.4).
    "myoLegWalk-v0": 1e-2,
    "myoLegRoughTerrainWalk-v0": 1e-2,
}


def _get_baseline_env_ids() -> list[str]:
    """Return env IDs that have a .pkl baseline file."""
    return [p.stem for p in sorted(BASELINE_DIR.glob("*.pkl"))]


@pytest.mark.parametrize("env_id", _get_baseline_env_ids())
def test_parity(env_id: str) -> None:
    """Replay frozen action sequence and assert numerical parity."""
    pkl_path = BASELINE_DIR / f"{env_id}.pkl"

    with open(pkl_path, "rb") as fh:
        records: list[dict] = pickle.load(fh)

    # A construction failure is a regression, so it fails rather than skips.
    env = gym.make(env_id)
    try:
        env.reset()
        current_episode_np_state = None

        for i, rec in enumerate(records):
            # When a new episode starts (np_state differs), restore the saved
            # RNG state and call env.reset() to reproduce the same initial obs.
            if rec["episode_np_state"] is not current_episode_np_state:
                current_episode_np_state = rec["episode_np_state"]
                env.unwrapped.np_random.bit_generator.state = current_episode_np_state
                env.reset()

            obs, rwd, terminated, truncated, _ = env.step(rec["action"])

            atol = RELAXED_OBS_ATOL.get(env_id, 1e-6)
            np.testing.assert_allclose(
                obs,
                rec["obs"],
                atol=atol,
                err_msg=f"{env_id} step {i}: obs mismatch",
            )
            rwd_atol = RELAXED_RWD_ATOL.get(env_id, 1e-6)
            assert (
                abs(rwd - rec["rwd"]) < rwd_atol
            ), f"{env_id} step {i}: reward mismatch (got {rwd}, expected {rec['rwd']})"
            assert (
                terminated == rec["terminated"]
            ), f"{env_id} step {i}: terminated mismatch"
            assert (
                truncated == rec["truncated"]
            ), f"{env_id} step {i}: truncated mismatch"
    finally:
        env.close()
