## FMG definitions from Daly et al. 2012 (doi.org/10.1123/japa.21.2.186) for shoulder, wrist, and elbow, from Rakshit et al. (doi.org/10.1016/j.jbiomech.2021.110695) for hand/grip, knee, and ankle, and from https://www.kenhub.com/en/library/anatomy/leg-muscles for legs
FUNCTIONAL_MUSCLE_GROUPS = {
    "Wrist-Extensor",
    "Wrist-Flexor",
    "Elbow-Extensor",
    "Elbow-Flexor",
    "Shoulder-Adductor",
    "Shoulder-Abductor",
    "Ankle-Dorsiflexor",
    "Ankle-Plantarflexor",
    "Hand-Adductor-Pollicis",
    "Hand-First-Dorsal-Interossei",
    # "Hand-Grip",  #incorporates wrist flexor (and extensor?) muscles
    "Knee-Extensor",  # also denoted as "Quadriceps group"
    "Toe-Flexor",
    ## The following groups were defined to capture the remaining muscles included in MyoSim models (also see https://www.kenhub.com/en/library/anatomy/hand-anatomy)
    "Hand-Interossei",
    "Hand-Lumbricals",  # also denoted as "Central compartment"
    "Hand-Thenar",
    "Hand-Hypothenar",
    "Hand-Palmaris-Brevis",
    "Hip-Extensor",
    "Hip-Flexor",
    "Hip-Abductor",
    "Hip-Lateral-Rotator",
    "Hip-Adductor",
    "Thigh-Hamstring",  # most of them are responsible for knee flexion and hip extension
    "Finger",  # used for myoFinger's joint torque actuators (see https://myosuite.readthedocs.io/en/latest/suite.html#myofinger)
}

MUSCLE_FMG = {
    "DELT1": "Shoulder-Abductor",
    "DELT2": "Shoulder-Abductor",
    "DELT3": "Shoulder-Abductor",
    "SUPSP": "Shoulder-Abductor",
    "INFSP": "Shoulder-Abductor",
    "SUBSC": "Shoulder-Abductor",
    "TMIN": "Shoulder-Adductor",
    "TMAJ": "Shoulder-Adductor",
    "PECM1": "Shoulder-Adductor",
    "PECM2": "Shoulder-Adductor",
    "PECM3": "Shoulder-Adductor",
    "LAT1": "Shoulder-Adductor",
    "LAT2": "Shoulder-Adductor",
    "LAT3": "Shoulder-Adductor",
    "CORB": "Shoulder-Adductor",
    "TRIlong": "Elbow-Extensor",
    "TRIlat": "Elbow-Extensor",
    "TRImed": "Elbow-Extensor",
    "ANC": "Elbow-Extensor",
    "SUP": "Elbow-Extensor",
    "BIClong": "Elbow-Flexor",
    "BICshort": "Elbow-Flexor",
    "BRA": "Elbow-Flexor",
    "BRD": "Elbow-Flexor",
    "ECRL": "Wrist-Extensor",
    "ECRB": "Wrist-Extensor",
    "ECU": "Wrist-Extensor",
    "FCR": "Wrist-Flexor",
    "FCU": "Wrist-Flexor",
    "PL": "Wrist-Flexor",
    "PT": "Elbow-Flexor",
    "PQ": "Wrist-Flexor",  # FMG chosen based on proximity to FDP and FPL
    "FDS5": "Wrist-Flexor",
    "FDS4": "Wrist-Flexor",
    "FDS3": "Wrist-Flexor",
    "FDS2": "Wrist-Flexor",
    "FDP5": "Wrist-Flexor",
    "FDP4": "Wrist-Flexor",
    "FDP3": "Wrist-Flexor",
    "FDP2": "Wrist-Flexor",
    "EDC5": "Wrist-Extensor",
    "EDC4": "Wrist-Extensor",
    "EDC3": "Wrist-Extensor",
    "EDC2": "Wrist-Extensor",
    "EDM": "Wrist-Extensor",
    "EIP": "Wrist-Extensor",
    "EPL": "Wrist-Extensor",
    "EPB": "Wrist-Extensor",
    "FPL": "Wrist-Flexor",
    "APL": "Wrist-Flexor",
    "OP": "Hand-Thenar",
    "RI2": "Hand-First-Dorsal-Interossei",  # "Hand-Interossei"
    "LU_RB2": "Hand-Lumbricals",
    "UI_UB2": "Hand-Interossei",
    "RI3": "Hand-Interossei",
    "LU_RB3": "Hand-Lumbricals",
    "UI_UB3": "Hand-Interossei",
    "RI4": "Hand-Interossei",
    "LU_RB4": "Hand-Lumbricals",
    "UI_UB4": "Hand-Interossei",
    "RI5": "Hand-Interossei",
    "LU_RB5": "Hand-Lumbricals",
    "UI_UB5": "Hand-Interossei",
    "extn": "Finger",
    "adabR": "Finger",
    "adabL": "Finger",
    "mflx": "Finger",
    "dflx": "Finger",
    "addbrev_l": "Hip-Adductor",
    "addbrev_r": "Hip-Adductor",
    "addlong_l": "Hip-Adductor",
    "addlong_r": "Hip-Adductor",
    "addmagDist_l": "Hip-Adductor",
    "addmagDist_r": "Hip-Adductor",
    "addmagIsch_l": "Hip-Adductor",
    "addmagIsch_r": "Hip-Adductor",
    "addmagMid_l": "Hip-Adductor",
    "addmagMid_r": "Hip-Adductor",
    "addmagProx_l": "Hip-Adductor",
    "addmagProx_r": "Hip-Adductor",
    "bflh_l": "Thigh-Hamstring",
    "bflh_r": "Thigh-Hamstring",
    "bfsh_l": "Thigh-Hamstring",
    "bfsh_r": "Thigh-Hamstring",
    "edl_l": "Ankle-Dorsiflexor",
    "edl_r": "Ankle-Dorsiflexor",
    "ehl_l": "Ankle-Dorsiflexor",
    "ehl_r": "Ankle-Dorsiflexor",
    "fdl_l": "Ankle-Plantarflexor",
    "fdl_r": "Ankle-Plantarflexor",
    "fhl_l": "Ankle-Plantarflexor",
    "fhl_r": "Ankle-Plantarflexor",
    "gaslat_l": "Ankle-Plantarflexor",
    "gaslat_r": "Ankle-Plantarflexor",
    "gasmed_l": "Ankle-Plantarflexor",
    "gasmed_r": "Ankle-Plantarflexor",
    "glmax1_l": "Hip-Extensor",
    "glmax1_r": "Hip-Extensor",
    "glmax2_l": "Hip-Extensor",
    "glmax2_r": "Hip-Extensor",
    "glmax3_l": "Hip-Extensor",
    "glmax3_r": "Hip-Extensor",
    "glmed1_l": "Hip-Flexor",  # "Hip-Abductor"
    "glmed1_r": "Hip-Flexor",  # "Hip-Abductor"
    "glmed2_l": "Hip-Abductor",
    "glmed2_r": "Hip-Abductor",
    "glmed3_l": "Hip-Extensor",  # "Hip-Abductor"
    "glmed3_r": "Hip-Extensor",  # "Hip-Abductor"
    "glmin1_l": "Hip-Abductor",
    "glmin1_r": "Hip-Abductor",
    "glmin2_l": "Hip-Abductor",
    "glmin2_r": "Hip-Abductor",
    "glmin3_l": "Hip-Abductor",
    "glmin3_r": "Hip-Abductor",
    "grac_l": "Hip-Adductor",  # "Hip-Flexor"
    "grac_r": "Hip-Adductor",  # "Hip-Flexor"
    "iliacus_l": "Hip-Flexor",
    "iliacus_r": "Hip-Flexor",
    "perbrev_l": "Ankle-Plantarflexor",
    "perbrev_r": "Ankle-Plantarflexor",
    "perlong_l": "Ankle-Plantarflexor",
    "perlong_r": "Ankle-Plantarflexor",
    "piri_l": "Hip-Lateral-Rotator",
    "piri_r": "Hip-Lateral-Rotator",
    "psoas_l": "Hip-Flexor",
    "psoas_r": "Hip-Flexor",
    "recfem_l": "Knee-Extensor",  # also "Hip-Flexor"
    "recfem_r": "Knee-Extensor",  # also "Hip-Flexor"
    "sart_l": "Hip-Flexor",  # "Thigh-Hamstring" (or rather "Knee-Flexor")
    "sart_r": "Hip-Flexor",  # "Thigh-Hamstring" (or rather "Knee-Flexor")
    "semimem_l": "Thigh-Hamstring",
    "semimem_r": "Thigh-Hamstring",
    "semiten_l": "Thigh-Hamstring",
    "semiten_r": "Thigh-Hamstring",
    "soleus_l": "Ankle-Plantarflexor",
    "soleus_r": "Ankle-Plantarflexor",
    "tfl_l": "Hip-Flexor",
    "tfl_r": "Hip-Flexor",
    "tibant_l": "Ankle-Dorsiflexor",
    "tibant_r": "Ankle-Dorsiflexor",
    "tibpost_l": "Ankle-Plantarflexor",
    "tibpost_r": "Ankle-Plantarflexor",
    "vasint_l": "Knee-Extensor",
    "vasint_r": "Knee-Extensor",
    "vaslat_l": "Knee-Extensor",
    "vaslat_r": "Knee-Extensor",
    "vasmed_l": "Knee-Extensor",
    "vasmed_r": "Knee-Extensor",
}
